name: jaguar_serializer
version: 0.1.9
description: Platform and format agnostic serializer built using source_gen
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: http://jaguar-dart.github.io

executables:
  serializer:

environment:
  sdk: ">=1.8.0 <2.0.0"

dependencies:
  source_gen: "^0.5.1"
  build: ">=0.4.1 <0.5.0"
  yaml: ">=2.1.10 <3.0.0"
  intl: ">=0.14.0 <0.15.0"
  yamlicious: ^0.0.5
  source_gen_help:
    git:
      url: https://github.com/Jaguar-dart/source_gen_help.git
      ref: 4acd8b6
  jaguar_generator_config:
    git:
      url: https://github.com/Jaguar-dart/jaguar_generator_config.git

dev_dependencies:
  test:
  mongo_dart:
