name: jaguar_serializer
version: 2.2.12
description: Platform and format agnostic serializer built using source_gen
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
- Hadrien Lejard <hadrien.lejard@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar_serializer
documentation:

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  build_runner: ^1.0.0
  jaguar_serializer_cli:
    path: ../serializer_cli