name: jaguar_serializer
version: 2.1.1
description: Platform and format agnostic serializer built using source_gen
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
- Hadrien Lejard <hadrien.lejard@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar_serializer
documentation:

environment:
  sdk: ">=2.0.0-dev <2.0.0"

dependencies:
  date_format: ^1.0.4

dev_dependencies:
  browser:
  test:
  intl: ">=0.15.0 <0.16.0"
  # yamlicious: ^0.0.5
  # yaml: ">=2.1.10 <3.0.0"
  build_runner: ^0.8.0
  jaguar_serializer_cli:
    path: ../jaguar_serializer_cli