name: jaguar_serializer_cli
version: 1.0.0-dev8
description: Platform and format agnostic serializer built using source_gen
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
- Hadrien Lejard <hadrien.lejard@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar_serializer

environment:
  sdk: ">=2.0.0-dev <2.0.0"

dependencies:
  analyzer: ^0.31.1
  build: ^0.12.0
  logging: ^0.11.0
  source_gen: ">=0.8.0 <0.9.0"
  jaguar_serializer: ^1.0.0-dev7

dependency_overrides:
  jaguar_serializer:
    path: ../jaguar_serializer

dev_dependencies:
  test: ^0.12.0
  build_runner: ^0.8.0
  build_test: ^0.10.0
  build_web_compilers: ^0.3.0